package development.gui;

import development.LoggedRequest;
import development.LoggedResponse;
import development.gui.model.RequestTableModel;
import development.gui.model.ResponseTableModel;
import java.awt.Color;
import java.awt.Dimension;
import logging.Logger;
import main.BESDyno;

/**
 *
 * @author emil
 */
public class LoggedCommPane extends javax.swing.JDialog {

    private static final Logger LOG = Logger.getLogger(LoggedCommPane.class.getName());

    private final RequestTableModel reqModel = new RequestTableModel();
    private final ResponseTableModel resModel = new ResponseTableModel();

    /**
     * Creates new form LoggedCommPane
     *
     * @param parent
     * @param modal
     */
    public LoggedCommPane(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(new Dimension(1000, 500));
        jTableReq.setModel(reqModel);
        jTableRes.setModel(resModel);
    }

    public void addRequest(LoggedRequest req) {
        reqModel.add(req);
    }

    public void addResponse(LoggedResponse res) {
        resModel.add(res);
    }

    public void rmAll() {
        reqModel.rmAll();
        resModel.rmAll();
    }

    public void setAppearance(boolean dark) {
        if (dark) {
            jTableReq.setBackground(Color.DARK_GRAY);
            jTableReq.setGridColor(Color.DARK_GRAY);
            jTableReq.getTableHeader().setBackground(Color.DARK_GRAY);
            jScrollPane3.setBackground(Color.DARK_GRAY);
            jScrollPane3.getViewport().setBackground(Color.DARK_GRAY);
            jScrollPane4.setBackground(Color.DARK_GRAY);
            jScrollPane4.getViewport().setBackground(Color.DARK_GRAY);
            jTableRes.setBackground(Color.DARK_GRAY);
            jTableRes.setGridColor(Color.DARK_GRAY);
            jTableRes.getTableHeader().setBackground(Color.DARK_GRAY);
            jPanButtons.setBackground(Color.DARK_GRAY);
            jPanTables.setBackground(Color.DARK_GRAY);

            jTableReq.setForeground(Color.WHITE);
            jTableReq.getTableHeader().setForeground(Color.WHITE);
            jTableRes.setForeground(Color.WHITE);
            jTableRes.getTableHeader().setForeground(Color.WHITE);
        } else {
            jTableReq.setBackground(Color.WHITE);
            jTableReq.setGridColor(Color.WHITE);
            jTableReq.getTableHeader().setBackground(Color.WHITE);
            jScrollPane3.setBackground(Color.WHITE);
            jScrollPane3.getViewport().setBackground(Color.WHITE);
            jScrollPane4.setBackground(Color.WHITE);
            jScrollPane4.getViewport().setBackground(Color.WHITE);
            jTableRes.setGridColor(Color.WHITE);
            jTableRes.setBackground(Color.WHITE);
            jTableRes.getTableHeader().setBackground(Color.WHITE);
            jPanButtons.setBackground(Color.WHITE);
            jPanTables.setBackground(Color.WHITE);

            jTableReq.setForeground(Color.BLACK);
            jTableReq.getTableHeader().setForeground(Color.BLACK);
            jTableRes.setForeground(Color.BLACK);
            jTableRes.getTableHeader().setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanButtons = new javax.swing.JPanel();
        jButSave = new javax.swing.JButton();
        jButOk = new javax.swing.JButton();
        jPanTables = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableReq = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableRes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanButtons.setLayout(new java.awt.GridBagLayout());

        jButSave.setText("Speichern");
        jButSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanButtons.add(jButSave, gridBagConstraints);

        jButOk.setText("OK");
        jButOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanButtons.add(jButOk, gridBagConstraints);

        getContentPane().add(jPanButtons, java.awt.BorderLayout.SOUTH);

        jPanTables.setLayout(new java.awt.GridLayout());

        jTableReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableReq);

        jPanTables.add(jScrollPane3);

        jTableRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableRes);

        jPanTables.add(jScrollPane4);

        getContentPane().add(jPanTables, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSaveActionPerformed
        try {
            BESDyno.getInstance().saveComm();
            LOG.info("Communication Log saved");
        } catch (Exception ex) {
            LOG.warning(ex);
        }
        dispose();
    }//GEN-LAST:event_jButSaveActionPerformed

    private void jButOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOkActionPerformed
        dispose();
    }//GEN-LAST:event_jButOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (System.getProperty("os.name").contains("Mac OS X")) {
                    if ("MAC OS X".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                } else {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoggedCommPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoggedCommPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoggedCommPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoggedCommPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            LoggedCommPane dialog = new LoggedCommPane(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    if (BESDyno.isDevMode()) {
                        BESDyno.saveCommAuto();
                        LOG.info("Communication Log saved");
                    }
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButOk;
    private javax.swing.JButton jButSave;
    private javax.swing.JPanel jPanButtons;
    private javax.swing.JPanel jPanTables;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableReq;
    private javax.swing.JTable jTableRes;
    // End of variables declaration//GEN-END:variables
}
