package gui;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author emil
 */
public class VehicleSetDialog extends javax.swing.JDialog {

    private boolean measRpm;
    private boolean twoStroke;
    private boolean automatic;
    private boolean schleppEnable;
    private String vehicleName;

    private boolean confirmed;

    /**
     * Creates new form VehicleSetDialog
     */
    public VehicleSetDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    //Getter & Setter
    public boolean isMeasRpm() {
        return measRpm;
    }

    public void setMeasRpm(boolean measRpm) {
        this.measRpm = measRpm;
    }

    public boolean isTwoStroke() {
        return twoStroke;
    }

    public void setTwoStroke(boolean twoStroke) {
        this.twoStroke = twoStroke;
    }

    public boolean isAutomatic() {
        return automatic;
    }

    public void setAutomatic(boolean automatic) {
        this.automatic = automatic;
    }

    public boolean isSchleppEnable() {
        return schleppEnable;
    }

    public void setSchleppEnable(boolean schleppEnable) {
        this.schleppEnable = schleppEnable;
    }

    public String getVehicleName() {
        return vehicleName;
    }

    public void setVehicleName(String vehicleName) {
        this.vehicleName = vehicleName;
    }

    public boolean isConfirmed() {
        return confirmed;
    }

    //Sets Appearance like at the Main-GUI
    public void setAppearance(boolean dark) {
        if (dark == true) {
            jPanButtons.setBackground(Color.darkGray);
            jPanControls.setBackground(Color.darkGray);
            jPanMain.setBackground(Color.darkGray);
            jPanName.setBackground(Color.darkGray);
            jPanRPM.setBackground(Color.darkGray);
            jPanStroke.setBackground(Color.darkGray);
            jPanTransmission.setBackground(Color.darkGray);
            jPanRPMCorr.setBackground(Color.darkGray);

            jLabelName.setForeground(Color.white);
            jLabelRPMCorr.setForeground(Color.white);
            jcbEnableRPM.setForeground(Color.white);
            jcbEnableSchlepp.setForeground(Color.white);
            jrb2Stroke.setForeground(Color.white);
            jrb4Stroke.setForeground(Color.white);
            jrbAutomatic.setForeground(Color.white);
            jrbManual.setForeground(Color.white);

            jtfVehicleName.setBackground(Color.darkGray);
            jtfRPMCorr.setBackground(Color.darkGray);

            jtfVehicleName.setForeground(Color.white);
            jtfRPMCorr.setForeground(Color.white);
        } else {
            jPanButtons.setBackground(Color.white);
            jPanControls.setBackground(Color.white);
            jPanMain.setBackground(Color.white);
            jPanName.setBackground(Color.white);
            jPanRPM.setBackground(Color.white);
            jPanStroke.setBackground(Color.white);
            jPanTransmission.setBackground(Color.white);
            jPanRPMCorr.setBackground(Color.white);

            jLabelName.setForeground(Color.black);
            jLabelRPMCorr.setForeground(Color.black);
            jcbEnableRPM.setForeground(Color.black);
            jcbEnableSchlepp.setForeground(Color.black);
            jrb2Stroke.setForeground(Color.black);
            jrb4Stroke.setForeground(Color.black);
            jrbAutomatic.setForeground(Color.black);
            jrbManual.setForeground(Color.black);

            jtfVehicleName.setBackground(Color.white);
            jtfRPMCorr.setBackground(Color.white);

            jtfVehicleName.setForeground(Color.black);
            jtfRPMCorr.setForeground(Color.white);
        }
    }

    //writeOut data
    private void confirm() {
        boolean error = false;

        measRpm = jcbEnableRPM.isSelected();
        twoStroke = jrb2Stroke.isSelected();
        automatic = jrbAutomatic.isSelected();
        schleppEnable = jcbEnableSchlepp.isSelected();

        if (jtfVehicleName.getText().length() > 25) {
            error = true;
            JOptionPane.showMessageDialog(this,
                    "Fahrzeugname darf nur maximal 25 Zeichen lang sein\n"
                    + "Aktuelle Zeichenlänge: "
                    + jtfVehicleName.getName().length(),
                    "Fahrzeugname zu lang!",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            vehicleName = jtfVehicleName.getText();
        }

        if (!error) {
            confirmed = true;
            dispose();
        } else {
            confirmed = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgStroke = new javax.swing.ButtonGroup();
        bgTransmission = new javax.swing.ButtonGroup();
        jPanMain = new javax.swing.JPanel();
        jPanName = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jtfVehicleName = new javax.swing.JTextField();
        jPanRPM = new javax.swing.JPanel();
        jcbEnableRPM = new javax.swing.JCheckBox();
        jcbEnableSchlepp = new javax.swing.JCheckBox();
        jPanRPMCorr = new javax.swing.JPanel();
        jLabelRPMCorr = new javax.swing.JLabel();
        jtfRPMCorr = new javax.swing.JTextField();
        jPanStroke = new javax.swing.JPanel();
        jrb2Stroke = new javax.swing.JRadioButton();
        jrb4Stroke = new javax.swing.JRadioButton();
        jPanTransmission = new javax.swing.JPanel();
        jrbManual = new javax.swing.JRadioButton();
        jrbAutomatic = new javax.swing.JRadioButton();
        jPanControls = new javax.swing.JPanel();
        jPanButtons = new javax.swing.JPanel();
        jbutCancel = new javax.swing.JButton();
        jbutStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanMain.setLayout(new java.awt.GridBagLayout());

        jPanName.setBackground(new java.awt.Color(255, 255, 255));
        jPanName.setLayout(new java.awt.GridBagLayout());

        jLabelName.setText("Fahrzeugname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanName.add(jLabelName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanName.add(jtfVehicleName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        jPanMain.add(jPanName, gridBagConstraints);

        jPanRPM.setBackground(new java.awt.Color(255, 255, 255));
        jPanRPM.setLayout(new java.awt.GridBagLayout());

        jcbEnableRPM.setText("Motordrehzahl messen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanRPM.add(jcbEnableRPM, gridBagConstraints);

        jcbEnableSchlepp.setText("Schleppleistung messen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanRPM.add(jcbEnableSchlepp, gridBagConstraints);

        jPanRPMCorr.setBackground(new java.awt.Color(255, 255, 255));
        jPanRPMCorr.setLayout(new java.awt.GridBagLayout());

        jLabelRPMCorr.setText("Motorleistung-Korrekturwert");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanRPMCorr.add(jLabelRPMCorr, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanRPMCorr.add(jtfRPMCorr, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        jPanRPM.add(jPanRPMCorr, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        jPanMain.add(jPanRPM, gridBagConstraints);

        jPanStroke.setBackground(new java.awt.Color(255, 255, 255));
        jPanStroke.setLayout(new java.awt.GridBagLayout());

        bgStroke.add(jrb2Stroke);
        jrb2Stroke.setText("2 Takt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanStroke.add(jrb2Stroke, gridBagConstraints);

        bgStroke.add(jrb4Stroke);
        jrb4Stroke.setText("4 Takt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanStroke.add(jrb4Stroke, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanMain.add(jPanStroke, gridBagConstraints);

        jPanTransmission.setBackground(new java.awt.Color(255, 255, 255));
        jPanTransmission.setLayout(new java.awt.GridBagLayout());

        bgTransmission.add(jrbManual);
        jrbManual.setText("Schaltgetriebe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanTransmission.add(jrbManual, gridBagConstraints);

        bgTransmission.add(jrbAutomatic);
        jrbAutomatic.setText("Automatik");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanTransmission.add(jrbAutomatic, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanMain.add(jPanTransmission, gridBagConstraints);

        getContentPane().add(jPanMain, java.awt.BorderLayout.CENTER);

        jPanControls.setBackground(new java.awt.Color(255, 255, 255));

        jPanButtons.setBackground(new java.awt.Color(255, 255, 255));
        jPanButtons.setLayout(new java.awt.GridLayout(1, 0));

        jbutCancel.setText("Abbrechen");
        jbutCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutCancelActionPerformed(evt);
            }
        });
        jPanButtons.add(jbutCancel);

        jbutStart.setText("Messung starten");
        jbutStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutStartActionPerformed(evt);
            }
        });
        jPanButtons.add(jbutStart);

        jPanControls.add(jPanButtons);

        getContentPane().add(jPanControls, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutStartActionPerformed
        confirm();
    }//GEN-LAST:event_jbutStartActionPerformed

    private void jbutCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutCancelActionPerformed
        confirmed = false;
        dispose();
    }//GEN-LAST:event_jbutCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the MAC OS X look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (System.getProperty("os.name").contains("Mac OS X")) {
                    if ("MAC OS X".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                } else {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeasureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeasureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeasureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeasureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            VehicleSetDialog dialog = new VehicleSetDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgStroke;
    private javax.swing.ButtonGroup bgTransmission;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRPMCorr;
    private javax.swing.JPanel jPanButtons;
    private javax.swing.JPanel jPanControls;
    private javax.swing.JPanel jPanMain;
    private javax.swing.JPanel jPanName;
    private javax.swing.JPanel jPanRPM;
    private javax.swing.JPanel jPanRPMCorr;
    private javax.swing.JPanel jPanStroke;
    private javax.swing.JPanel jPanTransmission;
    private javax.swing.JButton jbutCancel;
    private javax.swing.JButton jbutStart;
    private javax.swing.JCheckBox jcbEnableRPM;
    private javax.swing.JCheckBox jcbEnableSchlepp;
    private javax.swing.JRadioButton jrb2Stroke;
    private javax.swing.JRadioButton jrb4Stroke;
    private javax.swing.JRadioButton jrbAutomatic;
    private javax.swing.JRadioButton jrbManual;
    private javax.swing.JTextField jtfRPMCorr;
    private javax.swing.JTextField jtfVehicleName;
    // End of variables declaration//GEN-END:variables
}
